TASK 1

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
folder="/content/drive/MyDrive/Datasets"
os.makedirs(folder,exist_ok=True)

In [ ]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.4)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.6.17)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.16.0)

In [ ]:
import os

os.environ["bavatharani"] = "bavatharani"
os.environ["KGAT_420c9972c693b757811e72d2b60c4cb5"] = "KGAT_420c9972c693b757811e72d2b60c4cb5"

In [ ]:
!kaggle datasets download -d rohanrao/air-quality-data-in-india -p "/content/drive/MyDrive/Datasets"

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/rohanrao/air-quality-data-in-india
License(s): CC0-1.0
Downloading air-quality-data-in-india.zip to /content/drive/MyDrive/Datasets
100% 72.9M/72.9M [00:00<00:00, 115MB/s]

In [ ]:
!unzip "/content/drive/MyDrive/Datasets/air-quality-data-in-india.zip" -d "/content/drive/MyDrive/Datasets/kaggle"

Archive:  /content/drive/MyDrive/Datasets/air-quality-data-in-india.zip
  inflating: /content/drive/MyDrive/Datasets/kaggle/city_day.csv
  inflating: /content/drive/MyDrive/Datasets/kaggle/city_hour.csv
  inflating: /content/drive/MyDrive/Datasets/kaggle/station_day.csv
  inflating: /content/drive/MyDrive/Datasets/kaggle/station_hour.csv
  inflating: /content/drive/MyDrive/Datasets/kaggle/stations.csv

In [ ]:
!ls "/content/drive/MyDrive/Datasets/kaggle"

city_day.csv  city_hour.csv  station_day.csv  station_hour.csv	stations.csv

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Datasets/kaggle/city_day.csv")
print(df.head())

        City        Date  PM2.5  PM10     NO    NO2    NOx  NH3     CO    SO2  \
0  Ahmedabad  2015-01-01    NaN   NaN   0.92  18.22  17.15  NaN   0.92  27.64
1  Ahmedabad  2015-01-02    NaN   NaN   0.97  15.69  16.46  NaN   0.97  24.55
2  Ahmedabad  2015-01-03    NaN   NaN  17.40  19.30  29.70  NaN  17.40  29.07
3  Ahmedabad  2015-01-04    NaN   NaN   1.70  18.48  17.97  NaN   1.70  18.59
4  Ahmedabad  2015-01-05    NaN   NaN  22.10  21.42  37.76  NaN  22.10  39.33

       O3  Benzene  Toluene  Xylene  AQI AQI_Bucket
0  133.36     0.00     0.02    0.00  NaN        NaN
1   34.06     3.68     5.50    3.77  NaN        NaN
2   30.70     6.80    16.40    2.25  NaN        NaN
3   36.08     4.43    10.14    1.00  NaN        NaN
4   39.31     7.01    18.89    2.78  NaN        NaN

In [ ]:
!pip install -q datasets

In [ ]:
!pip install -U datasets huggingface_hub

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting datasets
  Downloading datasets-5.0.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.23.0)
Collecting huggingface_hub
  Downloading huggingface_hub-1.24.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.16.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-5.0.0-py3-none-any.whl (555 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 11.4 MB/s eta 0:00:00
Downloading huggingface_hub-1.24.0-py3-none-any.whl (771 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 771.9/771.9 kB 33.0 MB/s eta 0:00:00
Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (50.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 20.3 MB/s eta 0:00:00
Installing collected packages: pyarrow, huggingface_hub, datasets
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: huggingface_hub
    Found existing installation: huggingface_hub 1.23.0
    Uninstalling huggingface_hub-1.23.0:
      Successfully uninstalled huggingface_hub-1.23.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
Successfully installed datasets-5.0.0 huggingface_hub-1.24.0 pyarrow-25.0.0

In [ ]:
!pip install -U "datasets>=2.21.0"

Requirement already satisfied: datasets>=2.21.0 in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0) (3.29.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0) (2.0.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0) (25.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=2.21.0) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0) (1.24.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=2.21.0) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=2.21.0) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=2.21.0) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=2.21.0) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=2.21.0) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.21.0) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets>=2.21.0) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets>=2.21.0) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets>=2.21.0) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.21.0) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=2.21.0) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.21.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.21.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.21.0) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=2.21.0) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=2.21.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=2.21.0) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=2.21.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=2.21.0) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=2.21.0) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=2.21.0) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=2.21.0) (1.17.0)

In [ ]:
!pip show datasets

Name: datasets
Version: 5.0.0
Summary: HuggingFace community-driven open-source library of datasets
Home-page: https://github.com/huggingface/datasets
Author: HuggingFace Inc.
Author-email: thomas@huggingface.co
License: Apache 2.0
Location: /usr/local/lib/python3.12/dist-packages
Requires: dill, filelock, fsspec, httpx, huggingface-hub, multiprocess, numpy, packaging, pandas, pyarrow, pyyaml, requests, tqdm, xxhash
Required-by: torchtune

In [ ]:
!pip show huggingface_hub

Name: huggingface_hub
Version: 1.24.0
Summary: Client library to download and publish models, datasets and other repos on the huggingface.co hub
Home-page: https://github.com/huggingface/huggingface_hub
Author: Hugging Face, Inc.
Author-email: julien@huggingface.co
License: Apache-2.0
Location: /usr/local/lib/python3.12/dist-packages
Requires: click, filelock, fsspec, hf-xet, httpx, packaging, pyyaml, tqdm, typing-extensions
Required-by: accelerate, datasets, diffusers, gradio, gradio_client, peft, sentence-transformers, timm, tokenizers, torchtune, transformers

In [ ]:
!pip install -U datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (25.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.24.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [ ]:
!pip install -U datasets huggingface_hub

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.24.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (25.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.16.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [ ]:
!pip show datasets

Name: datasets
Version: 5.0.0
Summary: HuggingFace community-driven open-source library of datasets
Home-page: https://github.com/huggingface/datasets
Author: HuggingFace Inc.
Author-email: thomas@huggingface.co
License: Apache 2.0
Location: /usr/local/lib/python3.12/dist-packages
Requires: dill, filelock, fsspec, httpx, huggingface-hub, multiprocess, numpy, packaging, pandas, pyarrow, pyyaml, requests, tqdm, xxhash
Required-by: torchtune

In [ ]:
!pip show huggingface_hub

Name: huggingface_hub
Version: 1.24.0
Summary: Client library to download and publish models, datasets and other repos on the huggingface.co hub
Home-page: https://github.com/huggingface/huggingface_hub
Author: Hugging Face, Inc.
Author-email: julien@huggingface.co
License: Apache-2.0
Location: /usr/local/lib/python3.12/dist-packages
Requires: click, filelock, fsspec, hf-xet, httpx, packaging, pyyaml, tqdm, typing-extensions
Required-by: accelerate, datasets, diffusers, gradio, gradio_client, peft, sentence-transformers, timm, tokenizers, torchtune, transformers

In [ ]:
import datasets
import huggingface_hub

print(datasets.__version__)
print(huggingface_hub.__version__)

5.0.0
1.24.0

In [ ]:
!pip uninstall -y datasets huggingface_hub

Found existing installation: datasets 5.0.0
Uninstalling datasets-5.0.0:
  Successfully uninstalled datasets-5.0.0
Found existing installation: huggingface_hub 1.24.0
Uninstalling huggingface_hub-1.24.0:
  Successfully uninstalled huggingface_hub-1.24.0

In [ ]:
import datasets
import huggingface_hub

print(datasets.__version__)
print(huggingface_hub.__version__)

2.21.0
0.24.7

TASK 2

In [ ]:
!pip install -q datasets huggingface_hub pandas

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from huggingface_hub import hf_hub_download

file_path = hf_hub_download(
    repo_id="abhinavsarkar/delhi_air_quality_feature_store_unprocessed.csv",
    repo_type="dataset",
    filename="delhi_air_quality_feature_store_unprocessed.csv"
)

print(file_path)

(…)ir_quality_feature_store_unprocessed.csv:   0%|          | 0.00/615M [00:00<?, ?B/s]

/root/.cache/huggingface/hub/datasets--abhinavsarkar--delhi_air_quality_feature_store_unprocessed.csv/snapshots/e3c93ce853b7cecf6d0b46ea8faf580853ec200a/delhi_air_quality_feature_store_unprocessed.csv

In [ ]:
import pandas as pd

df = pd.read_csv(file_path)

print(df.head())

                                         location_id          city  \
0  Delhi Institute of Tool Engineering, Wazirpur,...      Wazirpur
1             Satyawati College, Delhi, Delhi, India         Delhi
2  ITI Shahdra, Jhilmil Industrial Area, Delhi, D...       Jhilmil
3  Sonia Vihar Water Treatment Plant DJB, Delhi, ...   Sonia Vihar
4   PGDAV College, Sriniwaspuri, Delhi, Delhi, India  Sriniwaspuri

              event_timestamp  temperature  humidity  pressure  wind_speed  \
0  2000-03-15 13:44:28.651396       30.450    74.100   990.425       0.300
1  2000-03-15 13:44:28.651396       26.675    74.350   980.650       1.375
2  2000-03-15 13:44:28.651396       28.775    62.925   984.350       0.300
3  2000-03-15 13:44:28.651396       26.575    78.525   991.300       0.300
4  2000-03-15 13:44:28.651396       22.300    71.425   985.650       0.300

   wind_direction   pm25   pm10   no2   so2    o3    co  aqi
0            21.7  252.0  332.0  62.4   4.8  22.4  35.7  332
1            55.3  256.0  234.0  59.2  11.9   2.1  33.8  256
2           221.3  265.0  210.0  48.3   5.1   8.2  35.1  265
3           313.6  251.0  177.0  16.5   1.8   1.7  24.9  251
4           347.1  282.0  347.0  43.1   5.2   3.4  29.9  347

In [ ]:
print(df.columns)

Index(['location_id', 'city', 'event_timestamp', 'temperature', 'humidity',
       'pressure', 'wind_speed', 'wind_direction', 'pm25', 'pm10', 'no2',
       'so2', 'o3', 'co', 'aqi'],
      dtype='object')

In [ ]:
df["event_timestamp"] = pd.to_datetime(df["event_timestamp"])

In [ ]:
filtered_df = df[
    (df["event_timestamp"].dt.year >= 2018) &
    (df["event_timestamp"].dt.year <= 2024)
]

In [ ]:
print(filtered_df.head())

                                               location_id          city  \
3265500  Delhi Institute of Tool Engineering, Wazirpur,...      Wazirpur
3265501             Satyawati College, Delhi, Delhi, India         Delhi
3265502  ITI Shahdra, Jhilmil Industrial Area, Delhi, D...       Jhilmil
3265503  Sonia Vihar Water Treatment Plant DJB, Delhi, ...   Sonia Vihar
3265504   PGDAV College, Sriniwaspuri, Delhi, Delhi, India  Sriniwaspuri

                   event_timestamp  temperature  humidity  pressure  \
3265500 2018-01-01 00:44:28.651396         33.7      50.7    965.05
3265501 2018-01-01 00:44:28.651396         31.3      48.0    982.70
3265502 2018-01-01 00:44:28.651396         33.7      42.1    984.00
3265503 2018-01-01 00:44:28.651396         33.5      43.3    978.20
3265504 2018-01-01 00:44:28.651396         28.1      44.3    987.60

         wind_speed  wind_direction   pm25   pm10   no2   so2     o3    co  \
3265500         0.3           350.4  195.0  170.0  25.4  11.5   84.3   2.8
3265501         1.5            54.4  209.0  172.0  12.8  14.2    2.2  13.6
3265502         0.3             1.8  200.0  379.0  15.0  12.9   42.3  13.4
3265503         0.3           200.7  211.0  162.0  11.4   7.0   91.9  38.0
3265504         0.3           174.9  192.0  139.0  16.1   5.2  103.0  14.7

         aqi
3265500  195
3265501  209
3265502  379
3265503  211
3265504  192

In [ ]:
filtered_df.to_csv(
    "/content/drive/MyDrive/Datasets/delhi_air_quality_2018_2024.csv",
    index=False
)

In [ ]:
print(df["event_timestamp"].min())
print(df["event_timestamp"].max())

2000-03-15 13:44:28.651396
2024-11-05 13:44:28.651396

In [ ]:
df["event_timestamp"] = pd.to_datetime(df["event_timestamp"])

In [ ]:
filtered_df = df[
    (df["event_timestamp"].dt.year >= 2018) &
    (df["event_timestamp"].dt.year <= 2024)
]

In [ ]:
print(filtered_df)

                                               location_id          city  \
3265500  Delhi Institute of Tool Engineering, Wazirpur,...      Wazirpur
3265501             Satyawati College, Delhi, Delhi, India         Delhi
3265502  ITI Shahdra, Jhilmil Industrial Area, Delhi, D...       Jhilmil
3265503  Sonia Vihar Water Treatment Plant DJB, Delhi, ...   Sonia Vihar
3265504   PGDAV College, Sriniwaspuri, Delhi, Delhi, India  Sriniwaspuri
...                                                    ...           ...
4468843                  North Campus, Delhi, Delhi, India  North Campus
4468844                   Civil Lines, Delhi, Delhi, India   Civil Lines
4468845                           ITO, Delhi, Delhi, India           ITO
4468846              ITI Jahangirpuri, Delhi, Delhi, India  Jahangirpuri
4468847                   Anand Vihar, Delhi, Delhi, India   Anand Vihar

                   event_timestamp  temperature  humidity  pressure  \
3265500 2018-01-01 00:44:28.651396        33.70      50.7    965.05
3265501 2018-01-01 00:44:28.651396        31.30      48.0    982.70
3265502 2018-01-01 00:44:28.651396        33.70      42.1    984.00
3265503 2018-01-01 00:44:28.651396        33.50      43.3    978.20
3265504 2018-01-01 00:44:28.651396        28.10      44.3    987.60
...                            ...          ...       ...       ...
4468843 2024-11-05 13:44:28.651396          NaN       NaN       NaN
4468844 2024-11-05 13:44:28.651396          NaN       NaN       NaN
4468845 2024-11-05 13:44:28.651396          NaN       NaN       NaN
4468846 2024-11-05 13:44:28.651396        26.65      65.3    974.95
4468847 2024-11-05 13:44:28.651396        27.95      61.8    980.80

         wind_speed  wind_direction   pm25   pm10   no2   so2     o3    co  \
3265500         0.3           350.4  195.0  170.0  25.4  11.5   84.3   2.8
3265501         1.5            54.4  209.0  172.0  12.8  14.2    2.2  13.6
3265502         0.3             1.8  200.0  379.0  15.0  12.9   42.3  13.4
3265503         0.3           200.7  211.0  162.0  11.4   7.0   91.9  38.0
3265504         0.3           174.9  192.0  139.0  16.1   5.2  103.0  14.7
...             ...             ...    ...    ...   ...   ...    ...   ...
4468843         3.6             NaN  164.0  157.0   7.7   NaN   12.6   0.1
4468844         NaN             NaN    NaN    NaN   NaN   NaN    NaN   NaN
4468845         NaN             NaN    NaN    NaN   NaN   NaN    NaN   NaN
4468846         0.3           137.3  235.0  256.0  31.0  11.2    2.5  38.7
4468847         0.3           249.1  240.0  561.0  30.0   7.5    4.0  21.5

         aqi
3265500  195
3265501  209
3265502  379
3265503  211
3265504  192
...      ...
4468843  164
4468844    -
4468845    -
4468846  256
4468847  561

[1203348 rows x 15 columns]

In [ ]:
filtered_df.to_csv(
    "/content/drive/MyDrive/Datasets/delhi_air_quality_2018_2024.csv",
    index=False
)

In [ ]:
print(filtered_df["event_timestamp"].min())
print(filtered_df["event_timestamp"].max())

2018-01-01 00:44:28.651396
2024-11-05 13:44:28.651396

In [ ]:
!ls /content/drive/MyDrive

'Colab Notebooks'   Datasets   IMG_20251211_185812.jpg	 Resume.pdf

In [ ]:
import urllib.request

years = [2019, 2020, 2021, 2022, 2023]

for year in years:
    url = f"https://github.com/Vonter/india-cpcb-aqi/releases/download/{year}/cpcb-air-quality-{year}.parquet"

    output = f"/content/drive/MyDrive/Datasets/cpcb-air-quality-{year}.parquet"

    urllib.request.urlretrieve(url, output)

    print(f"{year} downloaded successfully")

2019 downloaded successfully
2020 downloaded successfully
2021 downloaded successfully
2022 downloaded successfully
2023 downloaded successfully

In [ ]:
import pandas as pd

df = pd.read_parquet("/content/drive/MyDrive/Datasets/cpcb-air-quality-2019.parquet")

print(df.columns.tolist())

['Station ID', 'State', 'City', 'Station Name', 'Timestamp', 'PM2.5 (µg/m³)', 'PM10 (µg/m³)', 'NO (µg/m³)', 'NO2 (µg/m³)', 'NOx (ppb)', 'NH3 (µg/m³)', 'SO2 (µg/m³)', 'CO (mg/m³)', 'Ozone (µg/m³)', 'Benzene (µg/m³)', 'Toluene (µg/m³)', 'Xylene (µg/m³)', 'O Xylene (µg/m³)', 'Eth-Benzene (µg/m³)', 'MP-Xylene (µg/m³)', 'AT (°C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'RF (mm)', 'TOT-RF (mm)', 'SR (W/mt2)', 'BP (mmHg)', 'VWS (m/s)']

In [ ]:
print(df.columns.tolist())

['Station ID', 'State', 'City', 'Station Name', 'Timestamp', 'PM2.5 (µg/m³)', 'PM10 (µg/m³)', 'NO (µg/m³)', 'NO2 (µg/m³)', 'NOx (ppb)', 'NH3 (µg/m³)', 'SO2 (µg/m³)', 'CO (mg/m³)', 'Ozone (µg/m³)', 'Benzene (µg/m³)', 'Toluene (µg/m³)', 'Xylene (µg/m³)', 'O Xylene (µg/m³)', 'Eth-Benzene (µg/m³)', 'MP-Xylene (µg/m³)', 'AT (°C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'RF (mm)', 'TOT-RF (mm)', 'SR (W/mt2)', 'BP (mmHg)', 'VWS (m/s)']

In [ ]:
import pandas as pd
import os

years = [2019, 2020, 2021, 2022, 2023]

input_folder = "/content/drive/MyDrive/Datasets"
output_folder = "/content/drive/MyDrive/Delhi_Filtered"

os.makedirs(output_folder, exist_ok=True)

for year in years:
    print(f"Processing {year}...")

    file_path = f"{input_folder}/cpcb-air-quality-{year}.parquet"
    df = pd.read_parquet(file_path)

    # Filter only Delhi
    df_delhi = df[df["City"] == "Delhi"]

    # Required columns
    df_delhi = df_delhi[
        [
            "Station Name",
            "Timestamp",
            "PM2.5 (µg/m³)",
            "PM10 (µg/m³)",
            "NO2 (µg/m³)",
            "CO (mg/m³)",
            "Ozone (µg/m³)"
        ]
    ]

    output_path = f"{output_folder}/Delhi_{year}.parquet"
    df_delhi.to_parquet(output_path, index=False)

    print(f"{year} completed.")

print("✅ All files processed successfully!")

Processing 2019...
2019 completed.
Processing 2020...
2020 completed.
Processing 2021...
2021 completed.
Processing 2022...

TASK 3

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

In [ ]:
year = 2022

df = pd.read_parquet(f"/content/drive/MyDrive/Datasets/cpcb-air-quality-{year}.parquet")

df = df[df["City"] == "Delhi"]

df = df[
    [
        "Station Name",
        "Timestamp",
        "PM2.5 (µg/m³)",
        "PM10 (µg/m³)",
        "NO2 (µg/m³)",
        "CO (mg/m³)",
        "Ozone (µg/m³)"
    ]
]

df.to_parquet(f"/content/drive/MyDrive/Delhi_Filtered/Delhi_{year}.parquet", index=False)

print("2022 completed successfully")

2022 completed successfully

In [ ]:
year = 2023

df = pd.read_parquet(f"/content/drive/MyDrive/Datasets/cpcb-air-quality-{year}.parquet")

df = df[df["City"] == "Delhi"]

df = df[
    [
        "Station Name",
        "Timestamp",
        "PM2.5 (µg/m³)",
        "PM10 (µg/m³)",
        "NO2 (µg/m³)",
        "CO (mg/m³)",
        "Ozone (µg/m³)"
    ]
]

df.to_parquet(f"/content/drive/MyDrive/Delhi_Filtered/Delhi_{year}.parquet", index=False)

print("2023 completed successfully")

2023 completed successfully

In [ ]:
import pandas as pd

df = pd.read_parquet("/content/drive/MyDrive/Delhi_Filtered/Delhi_2023.parquet")

print(df)

                   Station Name                 Timestamp  PM2.5 (µg/m³)  \
0          Alipur, Delhi - DPCC 2023-01-01 00:00:00+00:00          134.0
1          Alipur, Delhi - DPCC 2023-01-01 00:15:00+00:00          134.0
2          Alipur, Delhi - DPCC 2023-01-01 00:30:00+00:00          134.0
3          Alipur, Delhi - DPCC 2023-01-01 00:45:00+00:00          134.0
4          Alipur, Delhi - DPCC 2023-01-01 01:00:00+00:00          112.0
...                         ...                       ...            ...
1362458  Wazirpur, Delhi - DPCC 2023-12-31 22:45:00+00:00          213.0
1362459  Wazirpur, Delhi - DPCC 2023-12-31 23:00:00+00:00          213.0
1362460  Wazirpur, Delhi - DPCC 2023-12-31 23:15:00+00:00          213.0
1362461  Wazirpur, Delhi - DPCC 2023-12-31 23:30:00+00:00          213.0
1362462  Wazirpur, Delhi - DPCC 2023-12-31 23:45:00+00:00          216.0

         PM10 (µg/m³)  NO2 (µg/m³)  CO (mg/m³)  Ozone (µg/m³)
0                 NaN         31.9         0.9            3.3
1               174.0         30.9         0.9            3.3
2               174.0         29.7         0.9            4.8
3               174.0         27.2         0.8            6.5
4               138.0         25.7         0.8            NaN
...               ...          ...         ...            ...
1362458         309.0         69.5         NaN            9.9
1362459         309.0         66.8         1.1            7.8
1362460         309.0         66.8         1.0            8.7
1362461         309.0         67.1         1.0            8.4
1362462         317.0         63.8         0.9            8.0

[1362463 rows x 7 columns]

In [ ]:
import pandas as pd

years = [2019, 2020, 2021, 2022, 2023]

dfs = []

for year in years:
    df = pd.read_parquet(f"/content/drive/MyDrive/Delhi_Filtered/Delhi_{year}.parquet")
    dfs.append(df)

final_df = pd.concat(dfs, ignore_index=True)

print(final_df)

                   Station Name                 Timestamp  PM2.5 (µg/m³)  \
0          Alipur, Delhi - DPCC 2019-01-01 00:00:00+00:00          338.0
1          Alipur, Delhi - DPCC 2019-01-01 00:15:00+00:00          338.0
2          Alipur, Delhi - DPCC 2019-01-01 00:30:00+00:00          385.0
3          Alipur, Delhi - DPCC 2019-01-01 00:45:00+00:00          385.0
4          Alipur, Delhi - DPCC 2019-01-01 01:00:00+00:00          385.0
...                         ...                       ...            ...
6820828  Wazirpur, Delhi - DPCC 2023-12-31 22:45:00+00:00          213.0
6820829  Wazirpur, Delhi - DPCC 2023-12-31 23:00:00+00:00          213.0
6820830  Wazirpur, Delhi - DPCC 2023-12-31 23:15:00+00:00          213.0
6820831  Wazirpur, Delhi - DPCC 2023-12-31 23:30:00+00:00          213.0
6820832  Wazirpur, Delhi - DPCC 2023-12-31 23:45:00+00:00          216.0

         PM10 (µg/m³)  NO2 (µg/m³)  CO (mg/m³)  Ozone (µg/m³)
0               512.0        145.1         3.8            1.2
1               512.0        165.1         4.8            1.8
2               539.0        170.0         3.6            1.3
3               539.0        147.4         3.3            NaN
4               539.0        146.6         2.6            NaN
...               ...          ...         ...            ...
6820828         309.0         69.5         NaN            9.9
6820829         309.0         66.8         1.1            7.8
6820830         309.0         66.8         1.0            8.7
6820831         309.0         67.1         1.0            8.4
6820832         317.0         63.8         0.9            8.0

[6820833 rows x 7 columns]

In [ ]:
import pandas as pd

years = [2019, 2020, 2021, 2022, 2023]

dfs = []

for year in years:
    df = pd.read_parquet(f"/content/drive/MyDrive/Delhi_Filtered/Delhi_{year}.parquet")
    dfs.append(df)

final_df = pd.concat(dfs, ignore_index=True)

# Print complete dataset
print(final_df)

# Display in proper table format in Colab
display(final_df)

                   Station Name                 Timestamp  PM2.5 (µg/m³)  \
0          Alipur, Delhi - DPCC 2019-01-01 00:00:00+00:00          338.0
1          Alipur, Delhi - DPCC 2019-01-01 00:15:00+00:00          338.0
2          Alipur, Delhi - DPCC 2019-01-01 00:30:00+00:00          385.0
3          Alipur, Delhi - DPCC 2019-01-01 00:45:00+00:00          385.0
4          Alipur, Delhi - DPCC 2019-01-01 01:00:00+00:00          385.0
...                         ...                       ...            ...
6820828  Wazirpur, Delhi - DPCC 2023-12-31 22:45:00+00:00          213.0
6820829  Wazirpur, Delhi - DPCC 2023-12-31 23:00:00+00:00          213.0
6820830  Wazirpur, Delhi - DPCC 2023-12-31 23:15:00+00:00          213.0
6820831  Wazirpur, Delhi - DPCC 2023-12-31 23:30:00+00:00          213.0
6820832  Wazirpur, Delhi - DPCC 2023-12-31 23:45:00+00:00          216.0

         PM10 (µg/m³)  NO2 (µg/m³)  CO (mg/m³)  Ozone (µg/m³)
0               512.0        145.1         3.8            1.2
1               512.0        165.1         4.8            1.8
2               539.0        170.0         3.6            1.3
3               539.0        147.4         3.3            NaN
4               539.0        146.6         2.6            NaN
...               ...          ...         ...            ...
6820828         309.0         69.5         NaN            9.9
6820829         309.0         66.8         1.1            7.8
6820830         309.0         66.8         1.0            8.7
6820831         309.0         67.1         1.0            8.4
6820832         317.0         63.8         0.9            8.0

[6820833 rows x 7 columns]

,Station Name,Timestamp,PM2.5 (µg/m³),PM10 (µg/m³),NO2 (µg/m³),CO (mg/m³),Ozone (µg/m³)
0,"Alipur, Delhi - DPCC",2019-01-01 00:00:00+00:00,338.0,512.0,145.1,3.8,1.2
1,"Alipur, Delhi - DPCC",2019-01-01 00:15:00+00:00,338.0,512.0,165.1,4.8,1.8
2,"Alipur, Delhi - DPCC",2019-01-01 00:30:00+00:00,385.0,539.0,170.0,3.6,1.3
3,"Alipur, Delhi - DPCC",2019-01-01 00:45:00+00:00,385.0,539.0,147.4,3.3,NaN
4,"Alipur, Delhi - DPCC",2019-01-01 01:00:00+00:00,385.0,539.0,146.6,2.6,NaN
...,...,...,...,...,...,...,...
6820828,"Wazirpur, Delhi - DPCC",2023-12-31 22:45:00+00:00,213.0,309.0,69.5,NaN,9.9
6820829,"Wazirpur, Delhi - DPCC",2023-12-31 23:00:00+00:00,213.0,309.0,66.8,1.1,7.8
6820830,"Wazirpur, Delhi - DPCC",2023-12-31 23:15:00+00:00,213.0,309.0,66.8,1.0,8.7
6820831,"Wazirpur, Delhi - DPCC",2023-12-31 23:30:00+00:00,213.0,309.0,67.1,1.0,8.4
6820832,"Wazirpur, Delhi - DPCC",2023-12-31 23:45:00+00:00,216.0,317.0,63.8,0.9,8.0

TASK 4

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd

# Read all yearly files
years = [2019, 2020, 2021, 2022, 2023]

dfs = []
for year in years:
    df = pd.read_parquet(f"/content/drive/MyDrive/Delhi_Filtered/Delhi_{year}.parquet")
    dfs.append(df)

# Merge
df = pd.concat(dfs, ignore_index=True)

# Rename columns
RENAME = {
    "Station Name": "station",
    "Timestamp": "timestamp",
    "PM2.5 (µg/m³)": "pm25",
    "PM10 (µg/m³)": "pm10",
    "NO2 (µg/m³)": "no2",
    "CO (mg/m³)": "co",
    "Ozone (µg/m³)": "o3",
}

df = df.rename(columns=RENAME)

# Convert timestamp to datetime
df["timestamp"] = pd.to_datetime(df["timestamp"])

# Sort by timestamp and station
df = df.sort_values(["timestamp", "station"]).reset_index(drop=True)

# Print dataset information
print(df)

# Display first 20 rows in proper table format
display(df.head(20))

# Save final dataset
df.to_parquet("/content/drive/MyDrive/Delhi_Filtered/Delhi_Final.parquet", index=False)

print("Rows :", len(df))
print("Stations :", df["station"].nunique())
print("Date Range :", df["timestamp"].min(), "->", df["timestamp"].max())

                                  station                 timestamp    pm25  \
0                    Alipur, Delhi - DPCC 2019-01-01 00:00:00+00:00  338.00
1               Anand Vihar, Delhi - DPCC 2019-01-01 00:00:00+00:00  513.00
2               Ashok Vihar, Delhi - DPCC 2019-01-01 00:00:00+00:00  393.00
3                  Aya Nagar, Delhi - IMD 2019-01-01 00:00:00+00:00  209.76
4                    Bawana, Delhi - DPCC 2019-01-01 00:00:00+00:00  128.00
...                                   ...                       ...     ...
6820828            Sirifort, Delhi - CPCB 2023-12-31 23:45:00+00:00     NaN
6820829         Sonia Vihar, Delhi - DPCC 2023-12-31 23:45:00+00:00  172.00
6820830  Sri Aurobindo Marg, Delhi - DPCC 2023-12-31 23:45:00+00:00  205.00
6820831         Vivek Vihar, Delhi - DPCC 2023-12-31 23:45:00+00:00  195.00
6820832            Wazirpur, Delhi - DPCC 2023-12-31 23:45:00+00:00  216.00

           pm10     no2    co     o3
0        512.00  145.10  3.80   1.20
1        951.00  178.80  4.90  20.80
2        561.00  151.50  3.70   2.00
3        394.74   25.23  1.33  34.69
4        477.00   59.60  1.90   3.00
...         ...     ...   ...    ...
6820828     NaN     NaN   NaN    NaN
6820829  243.00   19.70  1.20    NaN
6820830  292.00   43.30  1.10   3.60
6820831  325.00   17.00  0.80   3.60
6820832  317.00   63.80  0.90   8.00

[6820833 rows x 7 columns]

,station,timestamp,pm25,pm10,no2,co,o3
0,"Alipur, Delhi - DPCC",2019-01-01 00:00:00+00:00,338.00,512.00,145.10,3.80,1.20
1,"Anand Vihar, Delhi - DPCC",2019-01-01 00:00:00+00:00,513.00,951.00,178.80,4.90,20.80
2,"Ashok Vihar, Delhi - DPCC",2019-01-01 00:00:00+00:00,393.00,561.00,151.50,3.70,2.00
3,"Aya Nagar, Delhi - IMD",2019-01-01 00:00:00+00:00,209.76,394.74,25.23,1.33,34.69
4,"Bawana, Delhi - DPCC",2019-01-01 00:00:00+00:00,128.00,477.00,59.60,1.90,3.00
5,"Burari Crossing, Delhi - IMD",2019-01-01 00:00:00+00:00,356.49,558.48,43.23,2.80,24.24
6,"CRRI Mathura Road, Delhi - IMD",2019-01-01 00:00:00+00:00,497.89,775.16,32.98,6.59,48.52
7,"Chandni Chowk, Delhi - IITM",2019-01-01 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN
8,"DTU, Delhi - CPCB",2019-01-01 00:00:00+00:00,349.00,542.00,40.70,3.55,47.80
9,"Dr. Karni Singh Shooting Range, Delhi - DPCC",2019-01-01 00:00:00+00:00,360.00,566.00,69.40,3.40,20.00
10,"Dwarka-Sector 8, Delhi - DPCC",2019-01-01 00:00:00+00:00,509.00,838.00,58.90,5.90,1.80
11,"IGI Airport (T3), Delhi - IMD",2019-01-01 00:00:00+00:00,314.13,569.14,102.92,0.29,7.93
12,"IHBAS, Dilshad Garden, Delhi - CPCB",2019-01-01 00:00:00+00:00,338.60,NaN,86.89,NaN,NaN
13,"ITO, Delhi - CPCB",2019-01-01 00:00:00+00:00,451.00,543.00,82.50,7.25,4.49
14,"Jahangirpuri, Delhi - DPCC",2019-01-01 00:00:00+00:00,415.00,769.00,99.40,2.80,8.60
15,"Jawaharlal Nehru Stadium, Delhi - DPCC",2019-01-01 00:00:00+00:00,586.00,831.00,102.30,8.60,2.30
16,"Lodhi Road, Delhi - IITM",2019-01-01 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN
17,"Lodhi Road, Delhi - IMD",2019-01-01 00:00:00+00:00,355.01,538.67,41.31,3.92,19.92
18,"Major Dhyan Chand National Stadium, Delhi - DPCC",2019-01-01 00:00:00+00:00,NaN,738.00,72.00,7.40,2.00
19,"Mandir Marg, Delhi - DPCC",2019-01-01 00:00:00+00:00,396.00,433.00,NaN,1.60,6.90

Rows : 6820833
Stations : 39
Date Range : 2019-01-01 00:00:00+00:00 -> 2023-12-31 23:45:00+00:00

In [ ]:
# Print complete dataset information
print(df)

# Display dataset in proper rows and columns
display(df)

                                  station                 timestamp    pm25  \
0                    Alipur, Delhi - DPCC 2019-01-01 00:00:00+00:00  338.00
1               Anand Vihar, Delhi - DPCC 2019-01-01 00:00:00+00:00  513.00
2               Ashok Vihar, Delhi - DPCC 2019-01-01 00:00:00+00:00  393.00
3                  Aya Nagar, Delhi - IMD 2019-01-01 00:00:00+00:00  209.76
4                    Bawana, Delhi - DPCC 2019-01-01 00:00:00+00:00  128.00
...                                   ...                       ...     ...
6820828            Sirifort, Delhi - CPCB 2023-12-31 23:45:00+00:00     NaN
6820829         Sonia Vihar, Delhi - DPCC 2023-12-31 23:45:00+00:00  172.00
6820830  Sri Aurobindo Marg, Delhi - DPCC 2023-12-31 23:45:00+00:00  205.00
6820831         Vivek Vihar, Delhi - DPCC 2023-12-31 23:45:00+00:00  195.00
6820832            Wazirpur, Delhi - DPCC 2023-12-31 23:45:00+00:00  216.00

           pm10     no2    co     o3
0        512.00  145.10  3.80   1.20
1        951.00  178.80  4.90  20.80
2        561.00  151.50  3.70   2.00
3        394.74   25.23  1.33  34.69
4        477.00   59.60  1.90   3.00
...         ...     ...   ...    ...
6820828     NaN     NaN   NaN    NaN
6820829  243.00   19.70  1.20    NaN
6820830  292.00   43.30  1.10   3.60
6820831  325.00   17.00  0.80   3.60
6820832  317.00   63.80  0.90   8.00

[6820833 rows x 7 columns]

,station,timestamp,pm25,pm10,no2,co,o3
0,"Alipur, Delhi - DPCC",2019-01-01 00:00:00+00:00,338.00,512.00,145.10,3.80,1.20
1,"Anand Vihar, Delhi - DPCC",2019-01-01 00:00:00+00:00,513.00,951.00,178.80,4.90,20.80
2,"Ashok Vihar, Delhi - DPCC",2019-01-01 00:00:00+00:00,393.00,561.00,151.50,3.70,2.00
3,"Aya Nagar, Delhi - IMD",2019-01-01 00:00:00+00:00,209.76,394.74,25.23,1.33,34.69
4,"Bawana, Delhi - DPCC",2019-01-01 00:00:00+00:00,128.00,477.00,59.60,1.90,3.00
...,...,...,...,...,...,...,...
6820828,"Sirifort, Delhi - CPCB",2023-12-31 23:45:00+00:00,NaN,NaN,NaN,NaN,NaN
6820829,"Sonia Vihar, Delhi - DPCC",2023-12-31 23:45:00+00:00,172.00,243.00,19.70,1.20,NaN
6820830,"Sri Aurobindo Marg, Delhi - DPCC",2023-12-31 23:45:00+00:00,205.00,292.00,43.30,1.10,3.60
6820831,"Vivek Vihar, Delhi - DPCC",2023-12-31 23:45:00+00:00,195.00,325.00,17.00,0.80,3.60
6820832,"Wazirpur, Delhi - DPCC",2023-12-31 23:45:00+00:00,216.00,317.00,63.80,0.90,8.00

TASK 5

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_parquet(
    "/content/drive/MyDrive/Delhi_Filtered/Delhi_Final.parquet"
)

In [ ]:
POLLUTANT_COLS = [
    "pm25",
    "pm10",
    "no2",
    "co",
    "o3"
]

LIMITS = {
    "pm25": (0, 1000),
    "pm10": (0, 1500),
    "no2": (0, 700),
    "co": (0, 50),
    "o3": (0, 500),
}

In [ ]:
print("\n[2A] Cleaning each pollutant...")

for col in POLLUTANT_COLS:

    before_na = int(df[col].isna().sum())

    # Replace 999 with NaN
    df.loc[df[col] == 999, col] = np.nan

    # Remove values outside valid range
    low, high = LIMITS[col]

    df.loc[(df[col] < low) | (df[col] > high), col] = np.nan

    after_na = int(df[col].isna().sum())

    removed = after_na - before_na

    print(
        f"     {col:<5}: removed {removed} bad values "
        f"(now {df[col].isna().mean()*100:.1f}% blank)"
    )

[2A] Cleaning each pollutant...
     pm25 : removed 7 bad values (now 11.8% blank)
     pm10 : removed 3 bad values (now 13.9% blank)
     no2  : removed 0 bad values (now 12.6% blank)
     co   : removed 0 bad values (now 15.8% blank)
     o3   : removed 0 bad values (now 14.2% blank)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_parquet("/content/drive/MyDrive/Delhi_Filtered/Delhi_Final.parquet")

In [ ]:
print(df.head())
print(df.shape)

                     station                 timestamp    pm25    pm10  \
0       Alipur, Delhi - DPCC 2019-01-01 00:00:00+00:00  338.00  512.00
1  Anand Vihar, Delhi - DPCC 2019-01-01 00:00:00+00:00  513.00  951.00
2  Ashok Vihar, Delhi - DPCC 2019-01-01 00:00:00+00:00  393.00  561.00
3     Aya Nagar, Delhi - IMD 2019-01-01 00:00:00+00:00  209.76  394.74
4       Bawana, Delhi - DPCC 2019-01-01 00:00:00+00:00  128.00  477.00

      no2    co     o3
0  145.10  3.80   1.20
1  178.80  4.90  20.80
2  151.50  3.70   2.00
3   25.23  1.33  34.69
4   59.60  1.90   3.00
(6820833, 7)

In [ ]:
before_rows = len(df)

df = df[df["pm25"].notna()].copy()

removed_rows = before_rows - len(df)

print(f"\n[2A] Dropped rows with no PM2.5: {removed_rows:,}")
print(f"[2A] Rows left: {len(df):,}")

[2A] Dropped rows with no PM2.5: 806,990
[2A] Rows left: 6,013,843

In [ ]:
start = df["timestamp"].min()
end = df["timestamp"].max()

print(f"\n[2B] Date range: {start}  ->  {end}")

[2B] Date range: 2019-01-01 00:00:00+00:00  ->  2023-12-31 23:45:00+00:00

In [ ]:
hours = int((end - start).total_seconds() / 3600) + 1

print(f"[2B] Hours in the date range: {hours:,}")

[2B] Hours in the date range: 43,824

In [ ]:
coverage = (
    df.groupby("station")["pm25"]
      .count()
      .reset_index(name="hours_present")
)

coverage["coverage"] = (
    coverage["hours_present"] / hours
) * 100

coverage = coverage.sort_values(
    by="coverage",
    ascending=False
)

In [ ]:
print("\n[2B] Coverage per station (share of hours with PM2.5):")

for _, row in coverage.iterrows():

    status = "keep" if row["coverage"] >= 80 else "DROP"

    print(
        f"     {row['station']:<55}"
        f"{row['coverage']:5.1f}%   {status}"
    )

[2B] Coverage per station (share of hours with PM2.5):
     Okhla Phase-2, Delhi - DPCC                            388.8%   keep
     Major Dhyan Chand National Stadium, Delhi - DPCC       388.1%   keep
     Sri Aurobindo Marg, Delhi - DPCC                       387.8%   keep
     Dwarka-Sector 8, Delhi - DPCC                          386.6%   keep
     Nehru Nagar, Delhi - DPCC                              385.4%   keep
     Bawana, Delhi - DPCC                                   382.9%   keep
     CRRI Mathura Road, Delhi - IMD                         382.3%   keep
     Patparganj, Delhi - DPCC                               381.6%   keep
     Sonia Vihar, Delhi - DPCC                              381.5%   keep
     Mundka, Delhi - DPCC                                   380.0%   keep
     Jawaharlal Nehru Stadium, Delhi - DPCC                 379.6%   keep
     Dr. Karni Singh Shooting Range, Delhi - DPCC           377.0%   keep
     Wazirpur, Delhi - DPCC                                 376.7%   keep
     Vivek Vihar, Delhi - DPCC                              376.4%   keep
     Pusa, Delhi - DPCC                                     376.0%   keep
     NSIT Dwarka, Delhi - CPCB                              375.6%   keep
     Shadipur, Delhi - CPCB                                 375.1%   keep
     Lodhi Road, Delhi - IMD                                374.6%   keep
     Alipur, Delhi - DPCC                                   374.3%   keep
     Punjabi Bagh, Delhi - DPCC                             373.7%   keep
     Narela, Delhi - DPCC                                   371.1%   keep
     Ashok Vihar, Delhi - DPCC                              370.8%   keep
     Mandir Marg, Delhi - DPCC                              363.8%   keep
     Aya Nagar, Delhi - IMD                                 360.6%   keep
     Najafgarh, Delhi - DPCC                                359.6%   keep
     North Campus, DU, Delhi - IMD                          359.4%   keep
     Anand Vihar, Delhi - DPCC                              357.0%   keep
     Sirifort, Delhi - CPCB                                 356.6%   keep
     ITO, Delhi - CPCB                                      354.3%   keep
     IGI Airport (T3), Delhi - IMD                          353.3%   keep
     R K Puram, Delhi - DPCC                                352.6%   keep
     Rohini, Delhi - DPCC                                   351.0%   keep
     DTU, Delhi - CPCB                                      348.8%   keep
     Jahangirpuri, Delhi - DPCC                             347.7%   keep
     IHBAS, Dilshad Garden, Delhi - CPCB                    345.8%   keep
     Pusa, Delhi - IMD                                      337.6%   keep
     Burari Crossing, Delhi - IMD                           197.6%   keep
     Chandni Chowk, Delhi - IITM                            134.0%   keep
     Lodhi Road, Delhi - IITM                                97.2%   keep

In [ ]:
df.to_parquet(
    "/content/drive/MyDrive/Delhi_Filtered/Delhi_Cleaned.parquet",
    index=False
)

print("✅ Delhi_Cleaned.parquet saved successfully")

✅ Delhi_Cleaned.parquet saved successfully

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_parquet("/content/drive/MyDrive/Delhi_Filtered/Delhi_Cleaned.parquet")

In [ ]:
print(df.shape)

(6013843, 7)

In [ ]:
df = pd.read_parquet("/content/drive/MyDrive/Delhi_Filtered/Delhi_Final.parquet")

In [ ]:
print(df.head())

                     station                 timestamp    pm25    pm10  \
0       Alipur, Delhi - DPCC 2019-01-01 00:00:00+00:00  338.00  512.00
1  Anand Vihar, Delhi - DPCC 2019-01-01 00:00:00+00:00  513.00  951.00
2  Ashok Vihar, Delhi - DPCC 2019-01-01 00:00:00+00:00  393.00  561.00
3     Aya Nagar, Delhi - IMD 2019-01-01 00:00:00+00:00  209.76  394.74
4       Bawana, Delhi - DPCC 2019-01-01 00:00:00+00:00  128.00  477.00

      no2    co     o3
0  145.10  3.80   1.20
1  178.80  4.90  20.80
2  151.50  3.70   2.00
3   25.23  1.33  34.69
4   59.60  1.90   3.00

In [ ]:
print(df.columns)

Index(['station', 'timestamp', 'pm25', 'pm10', 'no2', 'co', 'o3'], dtype='object')

In [ ]:
print(df.shape)
print(df["station"].nunique())
print(df["timestamp"].min())
print(df["timestamp"].max())

(6820833, 7)
39
2019-01-01 00:00:00+00:00
2023-12-31 23:45:00+00:00

In [ ]:
df = pd.read_parquet("/content/drive/MyDrive/Delhi_Filtered/Delhi_Cleaned.parquet")
print(df.shape)

(6013843, 7)

In [ ]:
print(df.shape)

(6013843, 7)

In [ ]:
print("Total rows after cleaning:", len(df))

Total rows after cleaning: 6013843

In [ ]:
start = df["timestamp"].min()
end = df["timestamp"].max()

print(start, end)

2019-01-01 00:00:00+00:00 2023-12-31 23:45:00+00:00

In [ ]:
hours = int((end - start).total_seconds() / 3600) + 1

print("Hours:", hours)

Hours: 43824

In [ ]:
coverage = (
    df.groupby("station")["pm25"]
      .count()
      .reset_index(name="hours_present")
)

coverage["coverage"] = (
    coverage["hours_present"] / hours
) * 100

coverage = coverage.sort_values(
    by="coverage",
    ascending=False
)

In [ ]:
valid_stations = coverage.loc[
    coverage["coverage"] >= 50,
    "station"
]

df = df[df["station"].isin(valid_stations)].copy()

print("Remaining rows:", len(df))
print("Remaining stations:", df["station"].nunique())

Remaining rows: 6013843
Remaining stations: 39

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import os

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    for file in files:
        if file.endswith(".parquet") or file.endswith(".csv"):
            print(os.path.join(root, file))

/content/drive/MyDrive/Datasets/delhi_air_quality_2018_2024.csv
/content/drive/MyDrive/Datasets/cpcb-air-quality-2019.parquet
/content/drive/MyDrive/Datasets/cpcb-air-quality-2020.parquet
/content/drive/MyDrive/Datasets/cpcb-air-quality-2021.parquet
/content/drive/MyDrive/Datasets/cpcb-air-quality-2022.parquet
/content/drive/MyDrive/Datasets/cpcb-air-quality-2023.parquet
/content/drive/MyDrive/Delhi_Filtered/Delhi_2019.parquet
/content/drive/MyDrive/Delhi_Filtered/Delhi_2020.parquet
/content/drive/MyDrive/Delhi_Filtered/Delhi_2021.parquet
/content/drive/MyDrive/Delhi_Filtered/Delhi_2022.parquet
/content/drive/MyDrive/Delhi_Filtered/Delhi_2023.parquet
/content/drive/MyDrive/Delhi_Filtered/Delhi_Final.parquet
/content/drive/MyDrive/Delhi_Filtered/Delhi_Cleaned.parquet

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_parquet("/content/drive/MyDrive/Delhi_Filtered/Delhi_Cleaned.parquet")

print(df.shape)
df.head()

(6013843, 7)

,station,timestamp,pm25,pm10,no2,co,o3
0,"Alipur, Delhi - DPCC",2019-01-01 00:00:00+00:00,338.00,512.00,145.10,3.80,1.20
1,"Anand Vihar, Delhi - DPCC",2019-01-01 00:00:00+00:00,513.00,951.00,178.80,4.90,20.80
2,"Ashok Vihar, Delhi - DPCC",2019-01-01 00:00:00+00:00,393.00,561.00,151.50,3.70,2.00
3,"Aya Nagar, Delhi - IMD",2019-01-01 00:00:00+00:00,209.76,394.74,25.23,1.33,34.69
4,"Bawana, Delhi - DPCC",2019-01-01 00:00:00+00:00,128.00,477.00,59.60,1.90,3.00

In [ ]:
print(df.shape)

(6013843, 7)

In [ ]:
print(df["station"].nunique())
print(df["timestamp"].min())
print(df["timestamp"].max())

39
2019-01-01 00:00:00+00:00
2023-12-31 23:45:00+00:00

In [ ]:
coverage = (
    df.groupby("station")["pm25"]
      .count()
      .reset_index(name="hours_present")
)

start = df["timestamp"].min()
end = df["timestamp"].max()
hours = int((end - start).total_seconds() / 3600) + 1

coverage["coverage"] = (
    coverage["hours_present"] / hours
) * 100

coverage = coverage.sort_values("coverage")

print(coverage)

                                             station  hours_present  \
16                          Lodhi Road, Delhi - IITM          42612
7                        Chandni Chowk, Delhi - IITM          58742
5                       Burari Crossing, Delhi - IMD          86592
30                                 Pusa, Delhi - IMD         147955
12               IHBAS, Dilshad Garden, Delhi - CPCB         151538
14                        Jahangirpuri, Delhi - DPCC         152394
8                                  DTU, Delhi - CPCB         152840
32                              Rohini, Delhi - DPCC         153820
31                           R K Puram, Delhi - DPCC         154518
11                     IGI Airport (T3), Delhi - IMD         154818
13                                 ITO, Delhi - CPCB         155284
34                            Sirifort, Delhi - CPCB         156293
1                          Anand Vihar, Delhi - DPCC         156449
25                     North Campus, DU, Delhi - IMD         157495
22                           Najafgarh, Delhi - DPCC         157587
3                             Aya Nagar, Delhi - IMD         158019
19                         Mandir Marg, Delhi - DPCC         159424
2                          Ashok Vihar, Delhi - DPCC         162504
23                              Narela, Delhi - DPCC         162640
28                        Punjabi Bagh, Delhi - DPCC         163772
0                               Alipur, Delhi - DPCC         164012
17                           Lodhi Road, Delhi - IMD         164145
33                            Shadipur, Delhi - CPCB         164387
21                         NSIT Dwarka, Delhi - CPCB         164620
29                                Pusa, Delhi - DPCC         164764
37                         Vivek Vihar, Delhi - DPCC         164939
38                            Wazirpur, Delhi - DPCC         165088
9       Dr. Karni Singh Shooting Range, Delhi - DPCC         165204
15            Jawaharlal Nehru Stadium, Delhi - DPCC         166335
20                              Mundka, Delhi - DPCC         166536
35                         Sonia Vihar, Delhi - DPCC         167186
27                          Patparganj, Delhi - DPCC         167215
6                     CRRI Mathura Road, Delhi - IMD         167546
4                               Bawana, Delhi - DPCC         167810
24                         Nehru Nagar, Delhi - DPCC         168904
10                    Dwarka-Sector 8, Delhi - DPCC          169433
36                  Sri Aurobindo Marg, Delhi - DPCC         169955
18  Major Dhyan Chand National Stadium, Delhi - DPCC         170093
26                       Okhla Phase-2, Delhi - DPCC         170375

      coverage
16   97.234392
7   134.040708
5   197.590361
30  337.611811
12  345.787696
14  347.740964
8   348.758671
32  350.994889
31  352.587623
11  353.272180
13  354.335524
34  356.637915
1   356.993885
25  359.380705
22  359.590635
3   360.576396
19  363.782402
2   370.810515
23  371.120847
28  373.703907
0   374.251552
17  374.555038
33  375.107247
21  375.638919
29  375.967506
37  376.366831
38  376.706827
9   376.971522
15  379.552300
20  380.010953
35  381.494158
27  381.560332
6   382.315626
4   382.918036
24  385.414385
10  386.621486
36  387.812614
18  388.127510
26  388.770993

In [ ]:
start = df["timestamp"].min()
end = df["timestamp"].max()

hours = int((end - start).total_seconds() / 3600) + 1

coverage = (
    df.groupby("station")["pm25"]
      .count()
      .reset_index(name="hours_present")
)

coverage["coverage"] = (
    coverage["hours_present"] / hours
) * 100

coverage = coverage.sort_values("coverage")
print(coverage)

                                             station  hours_present  \
16                          Lodhi Road, Delhi - IITM          42612
7                        Chandni Chowk, Delhi - IITM          58742
5                       Burari Crossing, Delhi - IMD          86592
30                                 Pusa, Delhi - IMD         147955
12               IHBAS, Dilshad Garden, Delhi - CPCB         151538
14                        Jahangirpuri, Delhi - DPCC         152394
8                                  DTU, Delhi - CPCB         152840
32                              Rohini, Delhi - DPCC         153820
31                           R K Puram, Delhi - DPCC         154518
11                     IGI Airport (T3), Delhi - IMD         154818
13                                 ITO, Delhi - CPCB         155284
34                            Sirifort, Delhi - CPCB         156293
1                          Anand Vihar, Delhi - DPCC         156449
25                     North Campus, DU, Delhi - IMD         157495
22                           Najafgarh, Delhi - DPCC         157587
3                             Aya Nagar, Delhi - IMD         158019
19                         Mandir Marg, Delhi - DPCC         159424
2                          Ashok Vihar, Delhi - DPCC         162504
23                              Narela, Delhi - DPCC         162640
28                        Punjabi Bagh, Delhi - DPCC         163772
0                               Alipur, Delhi - DPCC         164012
17                           Lodhi Road, Delhi - IMD         164145
33                            Shadipur, Delhi - CPCB         164387
21                         NSIT Dwarka, Delhi - CPCB         164620
29                                Pusa, Delhi - DPCC         164764
37                         Vivek Vihar, Delhi - DPCC         164939
38                            Wazirpur, Delhi - DPCC         165088
9       Dr. Karni Singh Shooting Range, Delhi - DPCC         165204
15            Jawaharlal Nehru Stadium, Delhi - DPCC         166335
20                              Mundka, Delhi - DPCC         166536
35                         Sonia Vihar, Delhi - DPCC         167186
27                          Patparganj, Delhi - DPCC         167215
6                     CRRI Mathura Road, Delhi - IMD         167546
4                               Bawana, Delhi - DPCC         167810
24                         Nehru Nagar, Delhi - DPCC         168904
10                    Dwarka-Sector 8, Delhi - DPCC          169433
36                  Sri Aurobindo Marg, Delhi - DPCC         169955
18  Major Dhyan Chand National Stadium, Delhi - DPCC         170093
26                       Okhla Phase-2, Delhi - DPCC         170375

      coverage
16   97.234392
7   134.040708
5   197.590361
30  337.611811
12  345.787696
14  347.740964
8   348.758671
32  350.994889
31  352.587623
11  353.272180
13  354.335524
34  356.637915
1   356.993885
25  359.380705
22  359.590635
3   360.576396
19  363.782402
2   370.810515
23  371.120847
28  373.703907
0   374.251552
17  374.555038
33  375.107247
21  375.638919
29  375.967506
37  376.366831
38  376.706827
9   376.971522
15  379.552300
20  380.010953
35  381.494158
27  381.560332
6   382.315626
4   382.918036
24  385.414385
10  386.621486
36  387.812614
18  388.127510
26  388.770993

In [ ]:
coverage[coverage["coverage"] < 50]

Empty DataFrame
Columns: [station, hours_present, coverage]
Index: []

In [ ]:
valid_stations = coverage.loc[
    coverage["coverage"] >= 50,
    "station"
]

df = df[df["station"].isin(valid_stations)].copy()

print("=" * 70)
print("Stations remaining :", df["station"].nunique())
print("Rows remaining     :", len(df))
print("=" * 70)

======================================================================
Stations remaining : 39
Rows remaining     : 6013843
======================================================================

In [ ]:
print(df["station"].nunique())
print(df.shape)

39
(6013843, 7)

In [ ]:
print(hours)

43824

In [ ]:
coverage.sort_values("coverage").head(10)

                                station  hours_present    coverage
16             Lodhi Road, Delhi - IITM          42612   97.234392
7           Chandni Chowk, Delhi - IITM          58742  134.040708
5          Burari Crossing, Delhi - IMD          86592  197.590361
30                    Pusa, Delhi - IMD         147955  337.611811
12  IHBAS, Dilshad Garden, Delhi - CPCB         151538  345.787696
14           Jahangirpuri, Delhi - DPCC         152394  347.740964
8                     DTU, Delhi - CPCB         152840  348.758671
32                 Rohini, Delhi - DPCC         153820  350.994889
31              R K Puram, Delhi - DPCC         154518  352.587623
11        IGI Airport (T3), Delhi - IMD         154818  353.272180

In [ ]:
duplicates = df.duplicated(
    subset=["station", "timestamp"],
    keep=False
)

print("Duplicate rows:", duplicates.sum())

Duplicate rows: 0

In [ ]:
df[duplicates].head(20)

Empty DataFrame
Columns: [station, timestamp, pm25, pm10, no2, co, o3]
Index: []

In [ ]:
duplicates = df.duplicated(
    subset=["station", "timestamp"],
    keep=False
)

print("Duplicate rows:", duplicates.sum())

Duplicate rows: 0

In [ ]:
df[duplicates].sort_values(["station", "timestamp"]).head(20)

Empty DataFrame
Columns: [station, timestamp, pm25, pm10, no2, co, o3]
Index: []

In [ ]:
df["timestamp"] = pd.to_datetime(df["timestamp"])

print(df["timestamp"].dt.minute.value_counts().sort_index())

timestamp
0     1512542
15    1515190
30    1482366
45    1503745
Name: count, dtype: int64

In [ ]:
TASK 6

In [1]:
import pandas as pd

# Load cleaned dataset
df = pd.read_parquet("/content/drive/MyDrive/Delhi_Filtered/Delhi_Cleaned.parquet")

# Convert timestamp
df["timestamp"] = pd.to_datetime(df["timestamp"])

# Sort
df = df.sort_values(["station", "timestamp"])

# Create complete hourly timeline
start = df["timestamp"].min().floor("H")
end = df["timestamp"].max().ceil("H")

hours = pd.date_range(start=start, end=end, freq="1H")

stations = df["station"].unique()

full_index = pd.MultiIndex.from_product(
    [stations, hours],
    names=["station", "timestamp"]
)

df = (
    df.set_index(["station", "timestamp"])
      .reindex(full_index)
      .reset_index()
)

print("Rows after timeline:", len(df))

/tmp/ipykernel_2786/912565206.py:13: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start = df["timestamp"].min().floor("H")
/tmp/ipykernel_2786/912565206.py:14: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end = df["timestamp"].max().ceil("H")
/tmp/ipykernel_2786/912565206.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hours = pd.date_range(start=start, end=end, freq="1H")

Rows after timeline: 1709175

In [2]:
pollutants = ["pm25", "pm10", "no2", "co", "o3"]

for col in pollutants:
    before = df[col].isna().sum()

    df[col] = (
        df.groupby("station")[col]
          .ffill(limit=3)
    )

    after = df[col].isna().sum()

    print(f"{col:5} : filled {before-after} | still blank {after}")

pm25  : filled 53455 | still blank 143178
pm10  : filled 61141 | still blank 209658
no2   : filled 102972 | still blank 180354
co    : filled 148825 | still blank 183250
o3    : filled 120316 | still blank 189564

In [3]:
df.to_parquet(
    "/content/drive/MyDrive/Delhi_Filtered/Delhi_Hourly.parquet",
    index=False
)

print("Step 2C Completed")
print("Rows:", len(df))
print("Stations:", df["station"].nunique())

Step 2C Completed
Rows: 1709175
Stations: 39

In [4]:
print(df["timestamp"].min())
print(df["timestamp"].max())

2019-01-01 00:00:00+00:00
2024-01-01 00:00:00+00:00

In [5]:
print(df.groupby("station").size().unique())

[43825]

In [6]:
print(df.head())

                station                 timestamp   pm25   pm10    no2   co  \
0  Alipur, Delhi - DPCC 2019-01-01 00:00:00+00:00  338.0  512.0  145.1  3.8
1  Alipur, Delhi - DPCC 2019-01-01 01:00:00+00:00  385.0  539.0  146.6  2.6
2  Alipur, Delhi - DPCC 2019-01-01 02:00:00+00:00  311.0  489.0  146.6  2.6
3  Alipur, Delhi - DPCC 2019-01-01 03:00:00+00:00  285.0  444.0  120.1  1.7
4  Alipur, Delhi - DPCC 2019-01-01 04:00:00+00:00  268.0  415.0  109.1  1.9

     o3
0   1.2
1   1.2
2   2.1
3  10.2
4  10.0

In [7]:
import pandas as pd
import numpy as np

# Load hourly dataset
df = pd.read_parquet("/content/drive/MyDrive/Delhi_Filtered/Delhi_Hourly.parquet")

print(df.head())

print(df.columns)

                station                 timestamp   pm25   pm10    no2   co  \
0  Alipur, Delhi - DPCC 2019-01-01 00:00:00+00:00  338.0  512.0  145.1  3.8
1  Alipur, Delhi - DPCC 2019-01-01 01:00:00+00:00  385.0  539.0  146.6  2.6
2  Alipur, Delhi - DPCC 2019-01-01 02:00:00+00:00  311.0  489.0  146.6  2.6
3  Alipur, Delhi - DPCC 2019-01-01 03:00:00+00:00  285.0  444.0  120.1  1.7
4  Alipur, Delhi - DPCC 2019-01-01 04:00:00+00:00  268.0  415.0  109.1  1.9

     o3
0   1.2
1   1.2
2   2.1
3  10.2
4  10.0
Index(['station', 'timestamp', 'pm25', 'pm10', 'no2', 'co', 'o3'], dtype='object')

In [8]:
print(df.columns)

Index(['station', 'timestamp', 'pm25', 'pm10', 'no2', 'co', 'o3'], dtype='object')

In [9]:
AQI_BREAKPOINTS = {
    "pm25": [
        (0,30,0,50),
        (31,60,51,100),
        (61,90,101,200),
        (91,120,201,300),
        (121,250,301,400),
        (251,500,401,500)
    ],

    "pm10": [
        (0,50,0,50),
        (51,100,51,100),
        (101,250,101,200),
        (251,350,201,300),
        (351,430,301,400),
        (431,600,401,500)
    ],

    "no2": [
        (0,40,0,50),
        (41,80,51,100),
        (81,180,101,200),
        (181,280,201,300),
        (281,400,301,400),
        (401,1000,401,500)
    ],

    "co": [
        (0,1,0,50),
        (1.1,2,51,100),
        (2.1,10,101,200),
        (10.1,17,201,300),
        (17.1,34,301,400),
        (34.1,50,401,500)
    ],

    "o3": [
        (0,50,0,50),
        (51,100,51,100),
        (101,168,101,200),
        (169,208,201,300),
        (209,748,301,400),
        (749,1000,401,500)
    ]
}

print("Breakpoints Loaded Successfully")

Breakpoints Loaded Successfully

In [10]:
def calculate_subindex(value, pollutant):

    if pd.isna(value):
        return np.nan

    for BP_LO, BP_HI, I_LO, I_HI in AQI_BREAKPOINTS[pollutant]:

        if BP_LO <= value <= BP_HI:

            return ((I_HI - I_LO) / (BP_HI - BP_LO)) * (value - BP_LO) + I_LO

    return np.nan


print(calculate_subindex(338, "pm25"))

435.5903614457831

In [11]:
# Calculate sub-index for each pollutant
df["aqi_pm25"] = df["pm25"].apply(lambda x: calculate_subindex(x, "pm25"))
df["aqi_pm10"] = df["pm10"].apply(lambda x: calculate_subindex(x, "pm10"))
df["aqi_no2"]  = df["no2"].apply(lambda x: calculate_subindex(x, "no2"))
df["aqi_co"]   = df["co"].apply(lambda x: calculate_subindex(x, "co"))
df["aqi_o3"]   = df["o3"].apply(lambda x: calculate_subindex(x, "o3"))

# Final AQI = Maximum of all sub-indices
df["aqi"] = df[
    ["aqi_pm25", "aqi_pm10", "aqi_no2", "aqi_co", "aqi_o3"]
].max(axis=1)

print("AQI Calculated Successfully!")
print(df[["station", "timestamp", "aqi"]].head())

AQI Calculated Successfully!
                station                 timestamp         aqi
0  Alipur, Delhi - DPCC 2019-01-01 00:00:00+00:00  448.449704
1  Alipur, Delhi - DPCC 2019-01-01 01:00:00+00:00  464.266272
2  Alipur, Delhi - DPCC 2019-01-01 02:00:00+00:00  434.976331
3  Alipur, Delhi - DPCC 2019-01-01 03:00:00+00:00  414.518072
4  Alipur, Delhi - DPCC 2019-01-01 04:00:00+00:00  407.759036

In [12]:
print(df["aqi"].describe())

print(df["aqi"].isna().sum())

count    1.565982e+06
mean     2.079017e+02
std      1.251778e+02
min      0.000000e+00
25%      1.036577e+02
50%      1.694362e+02
75%      3.169072e+02
max      5.000000e+02
Name: aqi, dtype: float64
143193

In [13]:
# AQI summary

print("\nRows with AQI :", df["aqi"].notna().sum(), "/", len(df))
print("Unique AQI values :", df["aqi"].nunique())
print("Mean :", round(df["aqi"].mean(),2))
print("Std :", round(df["aqi"].std(),2))
print("Min :", round(df["aqi"].min(),2))
print("Max :", round(df["aqi"].max(),2))

Rows with AQI : 1565982 / 1709175
Unique AQI values : 84127
Mean : 207.9
Std : 125.18
Min : 0.0
Max : 500.0

In [14]:
df["year"] = df["timestamp"].dt.year

print("\nAQI Mean by Year")

yearly = df.groupby("year")["aqi"].agg(["mean","std"])

print(yearly.round(2))

AQI Mean by Year
        mean     std
year
2019  214.76  125.18
2020  188.66  124.69
2021  210.32  127.70
2022  215.01  121.61
2023  209.99  124.83
2024  341.56   61.97

In [15]:
df.to_csv(
    "/content/drive/MyDrive/Delhi_Filtered/delhi_cpcb_hourly.csv",
    index=False
)

print("\nFile Saved Successfully!")

File Saved Successfully!

In [16]:
display(df[[
    "station",
    "timestamp",
    "pm25",
    "pm10",
    "no2",
    "co",
    "o3",
    "aqi"
]].head())

,station,timestamp,pm25,pm10,no2,co,o3,aqi
0,"Alipur, Delhi - DPCC",2019-01-01 00:00:00+00:00,338.0,512.0,145.1,3.8,1.2,448.449704
1,"Alipur, Delhi - DPCC",2019-01-01 01:00:00+00:00,385.0,539.0,146.6,2.6,1.2,464.266272
2,"Alipur, Delhi - DPCC",2019-01-01 02:00:00+00:00,311.0,489.0,146.6,2.6,2.1,434.976331
3,"Alipur, Delhi - DPCC",2019-01-01 03:00:00+00:00,285.0,444.0,120.1,1.7,10.2,414.518072
4,"Alipur, Delhi - DPCC",2019-01-01 04:00:00+00:00,268.0,415.0,109.1,1.9,10.0,407.759036